### ISSUE TITLE
Game does crashes when i goes straight to south

### ISSUE THREAD

**Issue by WitchBeato** [findingfocus/tashio#1]
Error codes:
Error 

src/Map.lua:19: attempt to get length of field 'entities' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
src/Map.lua:19: in function 'init'
src/class.lua:79: in function 'Map'
src/Scene.lua:60: in function 'callback'
lib/knife/event.lua:66: in function 'dispatch'
src/Player.lua:137: in function 'update'
src/Scene.lua:141: in function 'update'
src/states/game/PlayState.lua:105: in function 'update'
src/StateMachine.lua:56: in function 'update'
main.lua:68: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by findingfocus** [comment]
Thank you for telling me about this, @WitchBeato. I've made a v1.1 release that fixes this issue.
